included:
  - TodoList
  - TodoListTests
  - TodoListUITests
disabled_rules:
  - trailing_whitespace
  - force_cast
  - multiple_closures_with_trailing_closure
line_length:
  warning: 180
  error: 200
function_parameter_count:
  warning: 6
  error: 10
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 400
  error: 800
